In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [79]:
df=pd.read_csv("/content/Copy of AWS Pre Assesment Test  Day 2.xlsx - Result AWS 1.csv")
print(df)

       .    1    2    3    4    5    6    7    8    9  ...   23   24   25  \
0    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN
1    hra  1.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0  ...  0.0  0.0  0.0
2    ira  1.0  1.0  1.0  1.0  0.0  1.0  0.0  1.0  1.0  ...  1.0  0.0  0.0
3    tal  1.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0  0.0  ...  1.0  0.0  0.0
4    ala  1.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0  0.0  ...  1.0  0.0  0.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
125  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN
126  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN
127  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN
128  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN
129  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN

      26   27  Total  Percentage  UNIQUE  Greater Than 50  GREATER Than 60
0    NaN  NaN    NaN         NaN     NaN              NaN              NaN
1    0.0  0.0   18.0       66.67    13.0             58.0              NaN
2    0.0  0.0   17.0       62.97    13.0              NaN              NaN
3    0.0  1.0   17.0       62.97    13.0              NaN              NaN
4    1.0  0.0   15.0       55.56    13.0              NaN              NaN
..   ...  ...    ...         ...     ...              ...              ...
125  NaN  NaN    1.0         NaN     NaN              NaN              NaN
126  NaN  NaN    2.0         NaN     NaN              NaN              NaN
127  NaN  NaN    3.0         NaN     NaN              NaN              NaN
128  NaN  NaN    1.0         NaN     NaN              NaN              NaN
129  NaN  NaN    3.0         NaN     NaN              NaN              NaN

[130 rows x 33 columns]

In [80]:
new_data = df[1:73]
new_data

,.,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,Total,Percentage,UNIQUE,Greater Than 50,GREATER Than 60
1,hra,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,18.0,66.67,13.0,58.0,NaN
2,ira,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,...,1.0,0.0,0.0,0.0,0.0,17.0,62.97,13.0,NaN,NaN
3,tal,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,...,1.0,0.0,0.0,0.0,1.0,17.0,62.97,13.0,NaN,NaN
4,ala,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,...,1.0,0.0,0.0,1.0,0.0,15.0,55.56,13.0,NaN,NaN
5,ndr,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,8.0,29.63,13.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,dra,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,0.0,1.0,19.0,70.38,5.0,NaN,NaN
69,bhc,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,0.0,1.0,1.0,1.0,20.0,74.08,4.0,NaN,NaN
70,agi,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,0.0,1.0,0.0,1.0,16.0,59.26,3.0,NaN,NaN
71,ain,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,0.0,1.0,0.0,1.0,18.0,66.67,2.0,NaN,NaN
72,aju,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,1.0,0.0,1.0,15.0,55.56,1.0,NaN,NaN

In [81]:
group = new_data.groupby('Percentage').size()
group

Percentage
29.63     1
33.34     2
37.04     4
40.75     3
44.45     2
48.15     2
51.86     2
55.56     7
59.26     7
62.97    10
66.67    21
70.38     4
74.08     7
dtype: int64

In [106]:
less_than_40=new_data[new_data['Percentage']<40]
less_than_40
print(len(less_than_40))

7

In [83]:
bt40_50=new_data[(new_data['Percentage']>=40) &( new_data['Percentage']<50)]
print(len(bt40_50))

7

In [84]:
bt50_60=new_data[(new_data['Percentage']>=50) &( new_data['Percentage']<60)]
print(len(bt50_60))

16

In [85]:
bt60_70=new_data[(new_data['Percentage']>=60) &( new_data['Percentage']<70)]
print(len(bt60_70))

31

In [86]:
bt70_80=new_data[(new_data['Percentage']>=70) &( new_data['Percentage']<80)]
print(len(bt70_80))

11

In [87]:
bt80_90=new_data[(new_data['Percentage']>=80) &( new_data['Percentage']<90)]
print(len(bt80_90))

0

In [88]:
bt90_100=new_data[(new_data['Percentage']>=90) &( new_data['Percentage']<100)]
print(len(bt90_100))

0

In [89]:
data = [less_than_40,bt40_50,bt50_60,bt60_70,bt70_80,bt80_90,bt90_100]
data = [len(i) for i in data]

In [58]:
groupby_data = pd.DataFrame({'Marks':['Less than 40','40-50','50-60','60-70','70-80','80-90','90-100']
                             ,'No of students':[less_than_40,bt40_50,bt50_60,bt60_70,bt70_80,bt80_90,bt90_100]})

In [90]:
groupby_data = pd.DataFrame({'Marks':['Less than 40','40-50','50-60','60-70','70-80','80-90','90-100']
                             ,'No of students':data})

In [91]:
groupby_data

          Marks  No of students
0  Less than 40               7
1         40-50               7
2         50-60              16
3         60-70              31
4         70-80              11
5         80-90               0
6        90-100               0

In [92]:
print(len(new_data))

72

In [93]:

conditions = [
    (new_data['Percentage'] < 60),
    (new_data['Percentage'] >= 60) & (new_data['Percentage'] < 70),
    (new_data['Percentage'] >= 70)
]
choices = ['Beginner', 'Intermediate', 'Advanced']

new_data['rating'] = np.select(conditions, choices, default='Not Rated')

/tmp/ipython-input-548/3394545829.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['rating'] = np.select(conditions, choices, default='Not Rated')

In [94]:
new_data['rating']

1     Intermediate
2     Intermediate
3     Intermediate
4         Beginner
5         Beginner
          ...
68        Advanced
69        Advanced
70        Beginner
71    Intermediate
72        Beginner
Name: rating, Length: 72, dtype: object

In [66]:
new_data.to_csv('outputfile.csv')

In [67]:
new_data.columns

Index(['.', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24',
       '25', '26', '27', 'Total', 'Percentage', 'UNIQUE', 'Greater Than 50',
       'GREATER Than 60', 'rating'],
      dtype='object')

In [69]:
new_data.head(5)

,.,1,2,3,4,5,6,7,8,9,...,24,25,26,27,Total,Percentage,UNIQUE,Greater Than 50,GREATER Than 60,rating
1,hra,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,18.0,66.67,13.0,58.0,NaN,Intermediate
2,ira,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,17.0,62.97,13.0,NaN,NaN,Intermediate
3,tal,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,1.0,17.0,62.97,13.0,NaN,NaN,Intermediate
4,ala,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,...,0.0,0.0,1.0,0.0,15.0,55.56,13.0,NaN,NaN,Beginer
5,ndr,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,29.63,13.0,NaN,NaN,Beginer

In [95]:
new_data = new_data.rename(columns = {'.':'Ids','rating':'Batch'})
new_data

,Ids,1,2,3,4,5,6,7,8,9,...,24,25,26,27,Total,Percentage,UNIQUE,Greater Than 50,GREATER Than 60,Batch
1,hra,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,18.0,66.67,13.0,58.0,NaN,Intermediate
2,ira,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,17.0,62.97,13.0,NaN,NaN,Intermediate
3,tal,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,1.0,17.0,62.97,13.0,NaN,NaN,Intermediate
4,ala,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,...,0.0,0.0,1.0,0.0,15.0,55.56,13.0,NaN,NaN,Beginner
5,ndr,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,29.63,13.0,NaN,NaN,Beginner
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,dra,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,0.0,1.0,19.0,70.38,5.0,NaN,NaN,Advanced
69,bhc,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,1.0,1.0,1.0,20.0,74.08,4.0,NaN,NaN,Advanced
70,agi,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,1.0,0.0,1.0,16.0,59.26,3.0,NaN,NaN,Beginner
71,ain,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,1.0,0.0,1.0,18.0,66.67,2.0,NaN,NaN,Intermediate
72,aju,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,...,0.0,1.0,0.0,1.0,15.0,55.56,1.0,NaN,NaN,Beginner

In [96]:
output = new_data[['Ids','Total','Percentage','Batch']]
output

    Ids  Total  Percentage         Batch
1   hra   18.0       66.67  Intermediate
2   ira   17.0       62.97  Intermediate
3   tal   17.0       62.97  Intermediate
4   ala   15.0       55.56      Beginner
5   ndr    8.0       29.63      Beginner
..  ...    ...         ...           ...
68  dra   19.0       70.38      Advanced
69  bhc   20.0       74.08      Advanced
70  agi   16.0       59.26      Beginner
71  ain   18.0       66.67  Intermediate
72  aju   15.0       55.56      Beginner

[72 rows x 4 columns]

In [98]:
output.to_csv('OutputFinal2.csv')

In [99]:
result = output.groupby('Batch').size()
result

Batch
Advanced        11
Beginner        30
Intermediate    31
dtype: int64

In [102]:
finalOutput = output.sort_values(by='Batch', ascending=False)
finalOutput

      Ids  Total  Percentage         Batch
1     hra   18.0       66.67  Intermediate
30    NaN   18.0       66.67  Intermediate
23    ana   18.0       66.67  Intermediate
24    del   17.0       62.97  Intermediate
54    har   18.0       66.67  Intermediate
..    ...    ...         ...           ...
68    dra   19.0       70.38      Advanced
69    bhc   20.0       74.08      Advanced
41  satti   20.0       74.08      Advanced
42    edi   19.0       70.38      Advanced
19    mar   19.0       70.38      Advanced

[72 rows x 4 columns]

In [103]:
finalOutput.to_csv('aswResult.csv')